### ISSUE TITLE
Apple Rejection - TMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by lrsanchez** [samzilverberg/cordova-mixpanel-plugin#104] opened 2019-06-05 12:53 UTC
Folks, 

I have been using the plugin for while, without no issues. Today I submitted a build to apple and got rejected. Here is the message:

TMS-90338: Non-public API usage - The app contains or inherits from non-public classes in xxxxx: WKInterfaceDevice . If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

Looking into my project I saw that this plugin is using this class on MixpanelWatchProperties.m

I think Apple is doing this by mistake because WKInterfaceDevice is public. Also, I have submitted the same App 4 days ago and it passed and its already available in the store.

Could you please advice how to workaround or bypass this issue ? 

Thank you 

Leandro

**Comment by cyrilgandon** [comment] 2019-06-05 14:49
I have opened an issue in https://github.com/mixpanel/mixpanel-iphone, since it is the same code. I hope to get more information from their part. There is no issue created for this problem on their part, so I don't know if their user have the same problem or not.

**Comment by KevinKelchen** [comment] 2019-06-05 18:43
Per the issue that @cyrilgandon opened, it looks like a new version of mixpanel-iphone was released: https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.4.6 . [The fix](https://github.com/mixpanel/mixpanel-iphone/commit/ddb5342b290e98521ee603a9707bdc168be1339c) was removing dead code.

This Cordova plugin would need to be updated to utilize it.

**Comment by samzilverberg** [comment] 2019-06-05 19:25
awesome.
upgrading from what the plugin currently uses (3.4.4) to 3.4.6 seems trivial, i'll try to get to it in the next hours,

**Comment by samzilverberg** [comment] 2019-06-05 20:13
4.6.2 is now out with latest ios and android sdk versions. 
give it a try and close the issue if everything is now fine for you

**Comment by lrsanchez** [comment] 2019-06-05 20:44
Thank you guys for the quick fix. I will give a try.

**Comment by jpike88** [comment] 2019-06-06 06:21
YES thanks for the fast fix.

**Comment by kadegray** [comment] 2019-06-06 09:17
@samzilverberg 4.6.2 still gets 'Non-public API usage'. I think it's because WKInterfaceDevice is still in MixpanelWatchProperties.m

**Comment by cyrilgandon** [comment] 2019-06-06 09:32
Yep, same here, even by deleting the stuff in Mixpanel.m, still refused.
We ended up by creating a fork and just removing everything, and it works...
https://github.com/laurant/cordova-mixpanel-plugin

**Comment by jpike88** [comment] 2019-06-06 09:56
Goddammit apple! Stupid false positives... I sent them an email over a day ago, and no response. This code is fine, it's not violating private api usage

**Comment by jpike88** [comment] 2019-06-06 11:32
this is what a grep gets me:

```
myapp/Plugins/cordova-plugin-advanced-http/AFURLResponseSerialization.m:    self.imageScale = [[WKInterfaceDevice currentDevice] screenScale];
myapp/Plugins/cordova-plugin-advanced-http/AFURLRequestSerialization.m:    userAgent = [NSString stringWithFormat:@"%@/%@ (%@; watchOS %@; Scale/%0.2f)", [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleExecutableKey] ?: [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleIdentifierKey], [[NSBundle mainBundle] infoDictionary][@"CFBundleShortVersionString"] ?: [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleVersionKey], [[WKInterfaceDevice currentDevice] model], [[WKInterfaceDevice currentDevice] systemVersion], [[WKInterfaceDevice currentDevice] screenScale]];
myapp/Plugins/cordova-plugin-mixpanel/Mixpanel/Mixpanel.m:    Class WKInterfaceDeviceClass = NSClassFromString(@"WKInterfaceDevice");
myapp/Plugins/cordova-plugin-mixpanel/Mixpanel/Mixpanel.m:    if (WKInterfaceDeviceClass) {
myapp/Plugins/cordova-plugin-mixpanel/Mixpanel/Mixpanel.m:        id device = ((id (*)(id, SEL))[WKInterfaceDeviceClass methodForSelector:currentDeviceSelector])(WKInterfaceDeviceClass, currentDeviceSelector);
myapp/Plugins/cordova-plugin-mixpanel/Mixpanel/MixpanelWatchProperties.m:    WKInterfaceDevice *device = [WKInterfaceDevice currentDevice];
myapp/Plugins/cordova-plugin-mixpanel/Mixpanel/MixpanelWatchProperties.m:    CGFloat screenWidth = [WKInterfaceDevice currentDevice].screenBounds.size.width;
myapp/Plugins/cordova-plugin-mixpanel/Mixpanel/MixpanelWatchProperties.m:    return [WKInterfaceDevice currentDevice].systemVersion;
./plugins/cordova-plugin-advanced-http/src/ios/AFNetworking/AFURLResponseSerialization.m:    self.imageScale = [[WKInterfaceDevice currentDevice] screenScale];
./plugins/cordova-plugin-advanced-http/src/ios/AFNetworking/AFURLRequestSerialization.m:    userAgent = [NSString stringWithFormat:@"%@/%@ (%@; watchOS %@; Scale/%0.2f)", [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleExecutableKey] ?: [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleIdentifierKey], [[NSBundle mainBundle] infoDictionary][@"CFBundleShortVersionString"] ?: [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleVersionKey], [[WKInterfaceDevice currentDevice] model], [[WKInterfaceDevice currentDevice] systemVersion], [[WKInterfaceDevice currentDevice] screenScale]];
./plugins/cordova-plugin-mixpanel/src/ios/Mixpanel/Mixpanel.m:    Class WKInterfaceDeviceClass = NSClassFromString(@"WKInterfaceDevice");
./plugins/cordova-plugin-mixpanel/src/ios/Mixpanel/Mixpanel.m:    if (WKInterfaceDeviceClass) {
./plugins/cordova-plugin-mixpanel/src/ios/Mixpanel/Mixpanel.m:        id device = ((id (*)(id, SEL))[WKInterfaceDeviceClass methodForSelector:currentDeviceSelector])(WKInterfaceDeviceClass, currentDeviceSelector);
./plugins/cordova-plugin-mixpanel/src/ios/Mixpanel/MixpanelWatchProperties.m:    WKInterfaceDevice *device = [WKInterfaceDevice currentDevice];
./plugins/cordova-plugin-mixpanel/src/ios/Mixpanel/MixpanelWatchProperties.m:    CGFloat screenWidth = [WKInterfaceDevice currentDevice].screenBounds.size.width;
./plugins/cordova-plugin-mixpanel/src/ios/Mixpanel/MixpanelWatchProperties.m:    return [WKInterfaceDevice currentDevice].systemVersion;
./node_modules/cordova-plugin-advanced-http/src/ios/AFNetworking/AFURLResponseSerialization.m:    self.imageScale = [[WKInterfaceDevice currentDevice] screenScale];
./node_modules/cordova-plugin-advanced-http/src/ios/AFNetworking/AFURLRequestSerialization.m:    userAgent = [NSString stringWithFormat:@"%@/%@ (%@; watchOS %@; Scale/%0.2f)", [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleExecutableKey] ?: [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleIdentifierKey], [[NSBundle mainBundle] infoDictionary][@"CFBundleShortVersionString"] ?: [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleVersionKey], [[WKInterfaceDevice currentDevice] model], [[WKInterfaceDevice currentDevice] systemVersion], [[WKInterfaceDevice currentDevice] screenScale]];
./node_modules/cordova-plugin-mixpanel/src/ios/Mixpanel/MixpanelWatchProperties.m:    WKInterfaceDevice *device = [WKInterfaceDevice currentDevice];
./node_modules/cordova-plugin-mixpanel/src/ios/Mixpanel/MixpanelWatchProperties.m:    CGFloat screenWidth = [WKInterfaceDevice currentDevice].screenBounds.size.width;
./node_modules/cordova-plugin-mixpanel/src/ios/Mixpanel/MixpanelWatchProperties.m:    return [WKInterfaceDevice currentDevice].systemVersion;
```

Anyone have any ideas?

**Comment by lrsanchez** [comment] 2019-06-06 16:59
> Goddammit apple! These are false positives... I sent them an email over a day ago, and no response. This code is fine, it's not violating private api usage

I did the same on my last submission, before post the issue here. They did not reply yet and I don´t know why they came with this now.

**Comment by lrsanchez** [comment] 2019-06-06 17:02
> Yep, same here, even by deleting the stuff in Mixpanel.m, still refused.
> We ended up by creating a fork and just removing everything, and it works...
> https://github.com/laurant/cordova-mixpanel-plugin

Good, I will give a try. Maybe @samzilverberg accept as permanent solution or maybe the guys from mixpanel-iphone came back with something else to fix it.

My client was in rush to release, I ended removed the plugin for now but I will test all the solutions available for next release.

Thank you all

**Comment by jpike88** [comment] 2019-06-07 02:20
```
id device = ((id (*)(id, SEL))[WKInterfaceDeviceClass methodForSelector:currentDeviceSelector])(WKInterfaceDeviceClass, currentDeviceSelector);
```

Could this be the issue?

**Comment by samzilverberg** [comment] 2019-06-07 07:53
@lrsanchez after patching the code on your fork did the submission to apple work?

looking at the thread on the mixpanel-iphone, i see there's already a suggestion to just remove references to `MixpanelWatchProperties` with a patch file.

i dont mind applying these to the code in the plugin and releasing 4.6.3, am just afraid it somehow might break someones app out there thats using this plugin...

i'd rather wait for an official fix from mixpanel-iphone than patching the code myself.
will give them another half a day and see if they release something.
this evening i'll try to release something anyway, either with their fix (hopefully) or with patching the code in this repo

**Comment by danishin** [comment] 2019-06-09 15:45
Hello @samzilverberg, can we patch the code in this repo and release new version like [this fork](https://github.com/laurant/cordova-mixpanel-plugin)? It seems like apple is taking some time to respond... Thanks!

**Comment by tamsel12** [comment] 2019-06-10 12:25
Here anybody finds the solution for this ? I have updated the cordova plugin for mixpanel version 4.6.2 . but still i am getting the same from apple

**Comment by snaptom** [comment] 2019-06-10 16:48
Can I confirm whether the forked approach has worked for anyone?

**Comment by jpike88** [comment] 2019-06-10 16:49
Yes, forked approach works.

https://github.com/laurant/cordova-mixpanel-plugin

**Comment by snaptom** [comment] 2019-06-10 16:51
awesome, thanks

**Comment by ecl66** [comment] 2019-06-10 17:46
I can confirm that Laurant's fork worked today. Thanks all!

**Comment by tamsel12** [comment] 2019-06-11 12:23
It's not working using this fork also https://github.com/laurant/cordova-mixpanel-plugin. 
So is there any other soultion for this issue?

**Comment by FIDELIX07** [comment] 2019-06-11 12:33
Not working

**Comment by KevinKelchen** [comment] 2019-06-11 16:07
I'm trying to test out the fork right now and am running into some configuration issues using a Git[Hub] URL with `cordova prepare`. We are using Cordova CLI 8.

For those who are using the fork, what's your `config.xml` and `package.json` configuration for the plugin? Or has someone packaged it and it's now hosted on the npm registry?

**Comment by samzilverberg** [comment] 2019-06-12 08:25
hi all, i hardly had any time in the last past days to publish the workaround to this issue.  it honestly doesn't look like I'll have time to do it at least until the weekend. i hope you're able to use the fork in the meanwhile and that mixpanel-iphone maintainers can post an official fix on their lib that is confirmed to work.

**Comment by kadegray** [comment] 2019-06-12 09:33
@KevinKelchen I used @cyrilgandon repo https://github.com/laurant/cordova-mixpanel-plugin.

After you have built ios do a find for 'WKInterfaceDevice' on the files of the project in xcode if it doesn't show up you're good. The issue i had is that the package was not updating after changing the npm version of cordova-mixpanel-plugin to the repo. I think i tried removing ios platform and adding it again and it didn't work, you could try it. If i remember what it was ill update here.

package.json
`"cordova-plugin-mixpanel": "github:laurant/cordova-mixpanel-plugin#master",`
 - would recommend forking this repo though

**Comment by kadegray** [comment] 2019-06-12 09:40
I think this is what worked:
`cordova plugin remove cordova-mixpanel-plugin`
`cordova plugin add github:laurant/cordova-mixpanel-plugin#master`

**Comment by tamsel12** [comment] 2019-06-12 09:41
> I think this is what worked:
> `cordova plugin remove cordova-mixpanel-plugin`
> `cordova plugin add github:laurant/cordova-mixpanel-plugin#master`

is this working for you without getting rejection from apple ?

**Comment by kadegray** [comment] 2019-06-12 09:44
@tamsel12 Yes, the key is to make sure WKInterfaceDevice is not in the ios code. Tomorrow i'll try to replicate the issue and confirm exactly what worked for me.

Keep in mind this isn't a long term solution. This depends on Apple resolving or explaining why they're flagging this.

**Comment by kadegray** [comment] 2019-06-12 13:12
@tamsel12 @KevinKelchen 

I can confirm it was this:
`ionic cordova plugin remove cordova-plugin-mixpanel` _(not cordova-mixpanel-plugin)_
`ionic cordova plugin add github:laurant/cordova-mixpanel-plugin#master`

If you are not using ionic i assume it would be the same if you omit ionic from the above commands.

If you do a find for WKInterfaceDevice after this there will be no results. Which means it will pass.

**Comment by snaptom** [comment] 2019-06-12 14:22
>I can confirm it was this:
@kadegray Thanks so much for this - we have been hitting exactly the same issue. Testing now

**Comment by tamsel12** [comment] 2019-06-12 15:11
>I can confirm it was this:
> `ionic cordova plugin remove cordova-plugin-mixpanel` _(not cordova-mixpanel-plugin)_
> `ionic cordova plugin add github:laurant/cordova-mixpanel-plugin#master`

Yes it is working now. Thanks @kadegray

**Comment by ecl66** [comment] 2019-06-13 07:28
Testing and will get back with results asap. Cheers.

**Comment by KevinKelchen** [comment] 2019-06-13 12:45
Thought it was worth mentioning my comment in the other issue here.

https://github.com/mixpanel/mixpanel-iphone/issues/850#issuecomment-501686452

**Comment by samzilverberg** [comment] 2019-06-15 12:17
ty @KevinKelchen for chasing this issue down with apple.
so as far as i understand, now everything works again? without needing any code changes?

**Comment by KevinKelchen** [comment] 2019-06-15 16:18
Hi @samzilverberg,

Yes, that's been my experience from the two builds/TestFlight uploads I've attempted with the plugin added back to our project (the latest official plugin release, v4.6.2, that incorporates `mixpanel-iphone` v3.4.6—not a fork and no code changes). I've only run those two builds/uploads (we've since migrated to `mixpanel-browser`) so my sample size for level of confidence isn't large, but I think the issue may be resolved given our experience.

I'd be interested to know if anyone else who has tried the latest official plugin release within the past couple of days has had success or not.

**Comment by coldiary** [comment] 2019-07-05 21:39
Unfortunately after patching this issue the first time with the fork, there is another issue, stated in the release note this time : 
> The WatchKit framework is no longer included in the iOS SDK. If you’re using WatchKit APIs from iOS, you need to remove this use. The WatchKit framework remains available on watchOS. If you’re using WatchKit APIs from iOS to infer availability of features on the paired Apple Watch, include information about your use case when you submit feedback to Feedback Assistant. (49707950)

([Complete release note here ](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_3_release_notes?language=objc))

This lead to the `WatchKit/WatchKit.h` header file missing when building from Xcode 11.
This need to be addressed again.

Since I don't really need the watch discovery feature, I'm going back to my fork, in the meantime.

**Comment by samzilverberg** [comment] 2019-07-06 14:42
@coldiary i see what you mean, but that's an issue with xcode 11 which is still beta. you can probably build without warnings with xcode 10.
it will be an issue in near future though xcode 11 is stable, but i assume will be resolved directly from the iPhone mixpanel lib.

**Comment by samzilverberg** [comment] 2019-08-01 11:42
closing for now.
looks like its gone with latest plugin and lib versions

**Closed by samzilverberg** 2019-08-01 11:42 UTC
